-- SCHEMA: senior_project
DROP TABLE IF EXISTS User_Recipes;
DROP TABLE IF EXISTS Users;


CREATE TABLE Users (
    UserId SERIAL PRIMARY KEY,
    Email TEXT NOT NULL,
    password TEXT NOT NULL,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);

CREATE TABLE User_Recipes(
    recipeId SERIAL PRIMARY KEY,
    VideoID VARCHAR NOT NULL,
    UserId INTEGER NOT NULL,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(UserId) REFERENCES Users(UserId)
);


CREATE SCHEMA IF NOT EXISTS senior_project
    AUTHORIZATION justin2;